# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='elevation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
